"""Ajout tables mÃ©tiers

Revision ID: ee0d902dd366
Revises: 867c5e66c089
Create Date: 2025-05-06 11:55:32.064350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee0d902dd366'
down_revision: Union[str, None] = '867c5e66c089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interactions_llm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('reponse', sa.Text(), nullable=True),
    sa.Column('modele', sa.String(), nullable=True),
    sa.Column('date_appel', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('montant', sa.Integer(), nullable=True),
    sa.Column('date_emission', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('clients', sa.Column('erp_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'erp_type')
    op.drop_table('tickets')
    op.drop_table('factures')
    op.drop_table('utilisateurs')
    op.drop_table('interactions_llm')
    # ### end Alembic commands ###
