name: Mirror to its

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Git and Mirror to ITS
        run: |
          git config --global user.email "p.perez@it-spirit.com"
          git config --global user.name "Philprz"
          git remote remove its || true
          # Secret configuré dans les paramètres GitHub comme "ENTREPRISE_TOKEN"
          git remote add its https://x-access-token:${{ secrets.ENTREPRISE_TOKEN }}@github.com/www-it-spirit-com/NOVAPOC.git
          git push its main --force

      - name: Notify failure (simple log visible dans l'interface GitHub)
        if: failure()
        run: |
          echo "❌ La synchronisation vers ITS a échoué."
